settings:
  legacy:
    force: false
    interval: 1s
schema:
- name: ygp-api
  path: /Users/psmarcin/projects/ygp-api
  commands:
    clean:
      status: false
    vet:
      status: false
    fmt:
      status: false
    test:
      status: false
    generate:
      status: false
    install:
      status: false
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
