name: Test
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install goimports
        run: GO111MODULE=off go get golang.org/x/tools/cmd/goimports

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test
